const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{ТайловыйФон: 0},
	{Кнопка: 0},
	{ф: 0},
	{первыйЭтаж: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{РЫЦАРЬ: 0},
	{Твёрдый: 0},
	{платформа: 0},
	{Синусоида: 0},
	{зомби: 0},
	{Пуля: 0},
	{оружие: 0},
	{Мышь: 0},
	{ТайловыйФон2: 0},
	{Текст: 0},
	{вМеню: 0},
	{Текст2: 0},
	{Спрайт: 0},
	{Текст3: 0},
	{ТайловыйФон3: 0},
	{препятствия: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{принц: 0},
	{Текст4: 0}
];

self.InstanceType = {
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Кнопка: class extends self.IButtonInstance {},
	ф: class extends self.ITextInstance {},
	первыйЭтаж: class extends self.ITiledBackgroundInstance {},
	РЫЦАРЬ: class extends self.ISpriteInstance {},
	платформа: class extends self.ISpriteInstance {},
	зомби: class extends self.ISpriteInstance {},
	оружие: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Текст: class extends self.ITextInstance {},
	вМеню: class extends self.IButtonInstance {},
	Текст2: class extends self.ITextInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	препятствия: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	принц: class extends self.ISpriteInstance {},
	Текст4: class extends self.ITextInstance {}
}